os:         linux
dist:       precise

language:   cpp

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake

script:
    - cd build
    - cmake ..
    - cmake --build .
    - ctest --output-on-failure
